(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



Clear[I0];

I0[-1,-1,-1,-1,-1,-1,a1_,a2_,a3_,a12_,a23_,a31_]=hI0[-1,-1,-1,-1,-1,-1,a1,a2,a3,a12,a23,a31];

I0[-1,-1,-1,-1,-1,n3_,a1_,a2_,a3_,a12_,a23_,a31_]:=
	I0[-1,-1,-1,-1,-1,n3,a1,a2,a3,a12,a23,a31]=
		-D[I0[-1,-1,-1,-1,-1,n3-1,a1,a2,a3,a12,a23,a31],a31];

I0[-1,-1,-1,-1,n2_,n3_,a1_,a2_,a3_,a12_,a23_,a31_]:=
	I0[-1,-1,-1,-1,n2,n3,a1,a2,a3,a12,a23,a31]=
		-D[I0[-1,-1,-1,-1,n2-1,n3,a1,a2,a3,a12,a23,a31],a23];

I0[-1,-1,-1,n1_,n2_,n3_,a1_,a2_,a3_,a12_,a23_,a31_]:=
	I0[-1,-1,-1,n1,n2,n3,a1,a2,a3,a12,a23,a31]=
		-D[I0[-1,-1,-1,n1-1,n2,n3,a1,a2,a3,a12,a23,a31],a12];

I0[-1,-1,M_,n1_,n2_,n3_,a1_,a2_,a3_,a12_,a23_,a31_]:=
	I0[-1,-1,M,n1,n2,n3,a1,a2,a3,a12,a23,a31]=
		-D[I0[-1,-1,M-1,n1,n2,n3,a1,a2,a3,a12,a23,a31],a3];

I0[-1,L_,M_,n1_,n2_,n3_,a1_,a2_,a3_,a12_,a23_,a31_]:=
	I0[-1,L,M,n1,n2,n3,a1,a2,a3,a12,a23,a31]=
		-D[I0[-1,L-1,M,n1,n2,n3,a1,a2,a3,a12,a23,a31],a2];

I0[K_,L_,M_,n1_,n2_,n3_,a1_,a2_,a3_,a12_,a23_,a31_]:=
	I0[K,L,M,n1,n2,n3,a1,a2,a3,a12,a23,a31]=
		-D[I0[K-1,L,M,n1,n2,n3,a1,a2,a3,a12,a23,a31],a1];



Clear[I2];

I2[-1,-1,-1,-1,-1,-1,a1_,a2_,a3_,a12_,a23_,a31_]=hI2[-1,-1,-1,-1,-1,-1,a1,a2,a3,a12,a23,a31];

I2[-1,-1,-1,-1,-1,n3_,a1_,a2_,a3_,a12_,a23_,a31_]:=
	I2[-1,-1,-1,-1,-1,n3,a1,a2,a3,a12,a23,a31]=
		-D[I2[-1,-1,-1,-1,-1,n3-1,a1,a2,a3,a12,a23,a31],a31];

I2[-1,-1,-1,-1,n2_,n3_,a1_,a2_,a3_,a12_,a23_,a31_]:=
	I2[-1,-1,-1,-1,n2,n3,a1,a2,a3,a12,a23,a31]=
		-D[I2[-1,-1,-1,-1,n2-1,n3,a1,a2,a3,a12,a23,a31],a23];

I2[-1,-1,-1,n1_,n2_,n3_,a1_,a2_,a3_,a12_,a23_,a31_]:=
	I2[-1,-1,-1,n1,n2,n3,a1,a2,a3,a12,a23,a31]=
		-D[I2[-1,-1,-1,n1-1,n2,n3,a1,a2,a3,a12,a23,a31],a12];

I2[-1,-1,M_,n1_,n2_,n3_,a1_,a2_,a3_,a12_,a23_,a31_]:=
	I2[-1,-1,M,n1,n2,n3,a1,a2,a3,a12,a23,a31]=
		-D[I2[-1,-1,M-1,n1,n2,n3,a1,a2,a3,a12,a23,a31],a3];

I2[-1,L_,M_,n1_,n2_,n3_,a1_,a2_,a3_,a12_,a23_,a31_]:=
	I2[-1,L,M,n1,n2,n3,a1,a2,a3,a12,a23,a31]=
		-D[I2[-1,L-1,M,n1,n2,n3,a1,a2,a3,a12,a23,a31],a2];

I2[K_,L_,M_,n1_,n2_,n3_,a1_,a2_,a3_,a12_,a23_,a31_]:=
	I2[K,L,M,n1,n2,n3,a1,a2,a3,a12,a23,a31]=
		-D[I2[K-1,L,M,n1,n2,n3,a1,a2,a3,a12,a23,a31],a1];



Clear[I3];

I3[-1,-1,-1,-1,-1,-1,a1_,a2_,a3_,a12_,a23_,a31_]=hI3[-1,-1,-1,-1,-1,-1,a1,a2,a3,a12,a23,a31];

I3[-1,-1,-1,-1,-1,n3_,a1_,a2_,a3_,a12_,a23_,a31_]:=
	I3[-1,-1,-1,-1,-1,n3,a1,a2,a3,a12,a23,a31]=
		-D[I3[-1,-1,-1,-1,-1,n3-1,a1,a2,a3,a12,a23,a31],a31];

I3[-1,-1,-1,-1,n2_,n3_,a1_,a2_,a3_,a12_,a23_,a31_]:=
	I3[-1,-1,-1,-1,n2,n3,a1,a2,a3,a12,a23,a31]=
		-D[I3[-1,-1,-1,-1,n2-1,n3,a1,a2,a3,a12,a23,a31],a23];

I3[-1,-1,-1,n1_,n2_,n3_,a1_,a2_,a3_,a12_,a23_,a31_]:=
	I3[-1,-1,-1,n1,n2,n3,a1,a2,a3,a12,a23,a31]=
		-D[I3[-1,-1,-1,n1-1,n2,n3,a1,a2,a3,a12,a23,a31],a12];

I3[-1,-1,M_,n1_,n2_,n3_,a1_,a2_,a3_,a12_,a23_,a31_]:=
	I3[-1,-1,M,n1,n2,n3,a1,a2,a3,a12,a23,a31]=
		-D[I3[-1,-1,M-1,n1,n2,n3,a1,a2,a3,a12,a23,a31],a3];

I3[-1,L_,M_,n1_,n2_,n3_,a1_,a2_,a3_,a12_,a23_,a31_]:=
	I3[-1,L,M,n1,n2,n3,a1,a2,a3,a12,a23,a31]=
		-D[I3[-1,L-1,M,n1,n2,n3,a1,a2,a3,a12,a23,a31],a2];

I3[K_,L_,M_,n1_,n2_,n3_,a1_,a2_,a3_,a12_,a23_,a31_]:=
	I3[K,L,M,n1,n2,n3,a1,a2,a3,a12,a23,a31]=
		-D[I3[K-1,L,M,n1,n2,n3,a1,a2,a3,a12,a23,a31],a1];



Clear[I4];

I4[-1,-1,-1,-1,-1,-1,a1_,a2_,a3_,a12_,a23_,a31_]=hI4[-1,-1,-1,-1,-1,-1,a1,a2,a3,a12,a23,a31];

I4[-1,-1,-1,-1,-1,n3_,a1_,a2_,a3_,a12_,a23_,a31_]:=
	I4[-1,-1,-1,-1,-1,n3,a1,a2,a3,a12,a23,a31]=
		-D[I4[-1,-1,-1,-1,-1,n3-1,a1,a2,a3,a12,a23,a31],a31];

I4[-1,-1,-1,-1,n2_,n3_,a1_,a2_,a3_,a12_,a23_,a31_]:=
	I4[-1,-1,-1,-1,n2,n3,a1,a2,a3,a12,a23,a31]=
		-D[I4[-1,-1,-1,-1,n2-1,n3,a1,a2,a3,a12,a23,a31],a23];

I4[-1,-1,-1,n1_,n2_,n3_,a1_,a2_,a3_,a12_,a23_,a31_]:=
	I4[-1,-1,-1,n1,n2,n3,a1,a2,a3,a12,a23,a31]=
		-D[I4[-1,-1,-1,n1-1,n2,n3,a1,a2,a3,a12,a23,a31],a12];

I4[-1,-1,M_,n1_,n2_,n3_,a1_,a2_,a3_,a12_,a23_,a31_]:=
	I4[-1,-1,M,n1,n2,n3,a1,a2,a3,a12,a23,a31]=
		-D[I4[-1,-1,M-1,n1,n2,n3,a1,a2,a3,a12,a23,a31],a3];

I4[-1,L_,M_,n1_,n2_,n3_,a1_,a2_,a3_,a12_,a23_,a31_]:=
	I4[-1,L,M,n1,n2,n3,a1,a2,a3,a12,a23,a31]=
		-D[I4[-1,L-1,M,n1,n2,n3,a1,a2,a3,a12,a23,a31],a2];

I4[K_,L_,M_,n1_,n2_,n3_,a1_,a2_,a3_,a12_,a23_,a31_]:=
	I4[K,L,M,n1,n2,n3,a1,a2,a3,a12,a23,a31]=
		-D[I4[K-1,L,M,n1,n2,n3,a1,a2,a3,a12,a23,a31],a1];



Clear[hIr];

hIr[K_,L_,M_,n1_,n2_,n3_,a1_,a2_,a3_,a12_,a23_,a31_]:=
	hIr[K,L,M,n1,n2,n3,a1,a2,a3,a12,a23,a31]=
	Module[
	   {s=\[Sigma]2[a1,a2,a3,a12,a23,a31],
		Y1=0.0125, Y2=-0.002,
		x,y,z,a,b,c,int},

		Which[
			s>Y1,
                int=I2[K,L,M,n1,n2,n3,x,y,z,a,b,c]/.{x->a1,y->a2,z->a3,a->a12,b->a23,c->a31}, 
            s==0, 
				int=I4[K,L,M,n1,n2,n3,x,y,z,a,b,c]/.{x->a1,y->a2,z->a3,a->a12,b->a23,c->a31}, 
            s>Y2, 
				int=I3[K,L,M,n1,n2,n3,x,y,z,a,b,c]/.{x->a1,y->a2,z->a3,a->a12,b->a23,c->a31}, 
			True, 
				int=I0[K,L,M,n1,n2,n3,x,y,z,a,b,c]/.{x->a1,y->a2,z->a3,a->a12,b->a23,c->a31}
       ];
	Re[int]   
];


Clear[pA, pC, pV, pW, pU];

pA[k_,a_]:=k!/a^(k+1);

pC[v_,q_,k_]:=(2q+1)/(v+2) Binomial[v+2,2k+1]\!\(
\*UnderoverscriptBox[\(\[Product]\), \(t = 0\), \(Min[q - 1, 
\*FractionBox[\(v + 1\), \(2\)]]\)]
\*FractionBox[\(2  k + 2  t - v\), \(2  k + 2  q - 2  t + 1\)]\);

pV[k_,l_,a_,b_]/;l>=0 := pV[k,l,a,b] =\!\(
\*UnderoverscriptBox[\(\[Sum]\), \(lp = 0\), \(l\)]\((Binomial[l, lp] pA[lp, b] pA[k + l - lp, a + b])\)\);
pV[k_,l_,a_,b_]/;l<0 := pV[k,l,a,b] = pA[k+l+1,a+b]/(k+1) Hypergeometric2F1[1,k+l+2,k+2,a/(a+b)];

pW[k_,l_,m_,a_,b_,c_]/;m>=0 := pW[k,l,m,a,b,c] = \!\(
\*UnderoverscriptBox[\(\[Sum]\), \(mp = 0\), \(m\)]\((Binomial[m, mp] pA[mp, c] pV[k, l + m - mp, a, b + c])\)\);
pW[k_,l_,m_,a_,b_,c_]/;m<0 := pW[k,l,m,a,b,c] = pA[k+l+m+2,b]\!\(
\*UnderoverscriptBox[\(\[Sum]\), \(lp = 0\), \(l\)]\((Binomial[l, lp] 
\*SuperscriptBox[\((\(-1\))\), \(lp\)] 
\*FractionBox[
SuperscriptBox[\(b\), \(k + m + 2\)], \(k + lp + m + 2\)]*\n\t\t\((
\*FractionBox[
SuperscriptBox[\(a\), \(lp\)], 
SuperscriptBox[\((a + b)\), \(k + lp + m + 2\)]] pU[k, lp, k + lp + m + 2, 
\*FractionBox[\(c\), \(a\)], 
\*FractionBox[\(c\), \(a + b\)]] - 
\*FractionBox[\(1\), 
SuperscriptBox[\(a\), \(k + m + 2\)]] pU[k, lp, k + lp + m + 2, 
\*FractionBox[\(c\), \(a\)], 
\*FractionBox[\(b + c\), \(a\)]])\))\)\);

pU[p_,q_,r_,x_,y_]:= pU[p,q,r,x,y] = \!\(
\*UnderoverscriptBox[\(\[Sum]\), \(qp = 0\), \(q\)]\((Binomial[q, qp] 
\*FractionBox[
SuperscriptBox[\(x\), \(q - qp\)], 
SuperscriptBox[\((y + 1)\), \(r\)]] 
\*FractionBox[\(1\), \(p + qp + 1\)] Hypergeometric2F1[1, r, p + qp + 2, 
\*FractionBox[\(1\), \(1 + y\)]])\)\);



Clear[I3ep];

(* l, m, n are even *)
I3ep[K_,L_,M_,l_?EvenQ,m_?EvenQ,n_?EvenQ,a1_,a2_,a3_]:= 
	I3ep[K,L,M,l,m,n,a1,a2,a3]=
		64\[Pi]^3*\!\(
\*UnderoverscriptBox[\(\[Sum]\), \(q = 0\), \(Min[l/2, m/2, n/2]\)]\((
\*FractionBox[\(1\), 
SuperscriptBox[\((2  q + 1)\), \(2\)]] \(
\*UnderoverscriptBox[\(\[Sum]\), \(i = 0\), \(l/2 - q\)]\((pC[l, q, i]*\n\t\t\t\(
\*UnderoverscriptBox[\(\[Sum]\), \(j = 0\), \(m/2 - q\)]\((pC[m, q, j] \(
\*UnderoverscriptBox[\(\[Sum]\), \(k = 0\), \(n/2 - q\)]\((pC[n, q, k] pA[K + 2 + m - 2  j + 2  k, a1] pA[L + 2 + 2  i + n - 2  k, a2] pA[M + 2 + l - 2  i + 2  j, a3])\)\))\)\))\)\))\)\);


(* any of l, m, n is odd *)
I3ep[K_,L_,M_,l_?OddQ,m_?EvenQ,n_?EvenQ,a1_,a2_,a3_]:= 
	I3ep[K,L,M,l,m,n,a1,a2,a3]=
		64\[Pi]^3*\!\(
\*UnderoverscriptBox[\(\[Sum]\), \(q = 0\), \(Min[m/2, n/2]\)]\((
\*FractionBox[\(1\), 
SuperscriptBox[\((2  q + 1)\), \(2\)]] \(
\*UnderoverscriptBox[\(\[Sum]\), \(i = 0\), \(\((l + 1)\)/2\)]\((pC[l, q, i]*\n\t\t\t\t\t\t\ \ \ \t\(
\*UnderoverscriptBox[\(\[Sum]\), \(j = 0\), \(m/2 - q\)]\((pC[m, q, j] \(
\*UnderoverscriptBox[\(\[Sum]\), \(k = 0\), \(n/2 - q\)]\((pC[n, q, k] pA[K + 2 + m - 2  j + 2  k, a1]*\n\t\t\t\t\t\t\t\t\t\((pV[L + 2 + 2  i + n - 2  k, M + 2 + l - 2  i + 2  j, a2, a3] + \n\t\t\t\t\t\t\t\t\t\ pV[M + 2 + 2  q + 2  i + 2  j, L + 2 - 2  q + l - 2  i + n - 2  k, a3, a2])\))\)\))\)\))\)\))\)\);


I3ep[K_,L_,M_,l_?EvenQ,m_?OddQ,n_?EvenQ,a1_,a2_,a3_]:= I3ep[L,K,M,m,l,n,a2,a1,a3];

I3ep[K_,L_,M_,l_?EvenQ,m_?EvenQ,n_?OddQ,a1_,a2_,a3_]:= I3ep[M,L,K,n,m,l,a3,a2,a1];


(* any of l, m, n is even *)
I3ep[K_,L_,M_,l_?OddQ,m_?OddQ,n_?EvenQ,a1_,a2_,a3_]:= 
	I3ep[K,L,M,l,m,n,a1,a2,a3]=
		64\[Pi]^3*\!\(
\*UnderoverscriptBox[\(\[Sum]\), \(q = 0\), \(n/2\)]\((
\*FractionBox[\(1\), 
SuperscriptBox[\((2  q + 1)\), \(2\)]] \(
\*UnderoverscriptBox[\(\[Sum]\), \(i = 0\), \(\((l + 1)\)/2\)]\((pC[l, q, i] \(
\*UnderoverscriptBox[\(\[Sum]\), \(j = 0\), \(\((m + 1)\)/2\)]\((pC[m, q, j] \(
\*UnderoverscriptBox[\(\[Sum]\), \(k = 0\), \(n/2 - q\)]\((pC[n, q, k]*\n\t\t\t\((pW[K + 2 + 2  q + 2  j + 2  k, L + 2 + 2  i + n - 2  k, M + 2 - 2  q + l - 2  i + m - 2  j, a1, a2, a3] + \n\t\t\t\ pW[K + 2 + 2  q + 2  j + 2  k, M + 2 + 2  i + m - 2  j, L + 2 - 2  q + l - 2  i + n - 2  k, a1, a3, a2] + \n\t\t\t\ pW[L + 2 + 2  q + 2  i + 2  k, K + 2 + 2  j + n - 2  k, M + 2 - 2  q + l - 2  i + m - 2  j, a2, a1, a3] + \n\t\t\t\ pW[L + 2 + 2  q + 2  i + 2  k, M + 2 + 2  j + l - 2  i, K + 2 - 2  q + m - 2  j + n - 2  k, a2, a3, a1] + \n\t\t\t\ pW[M + 2 + 2  q + 2  i + 2  j, K + 2 + 2  k + m - 2  j, L + 2 - 2  q + l - 2  i + n - 2  k, a3, a1, a2] + \n\t\t\t\ pW[M + 2 + 2  q + 2  i + 2  j, L + 2 + 2  k + l - 2  i, K + 2 - 2  q + m - 2  j + n - 2  k, a3, a2, a1])\))\)\)\n\t\t)\)\))\)\))\)\);

I3ep[K_,L_,M_,l_?OddQ,m_?EvenQ,n_?OddQ,a1_,a2_,a3_]:=I3ep[K,M,L,l,n,m,a1,a3,a2];
I3ep[K_,L_,M_,l_?EvenQ,m_?OddQ,n_?OddQ,a1_,a2_,a3_]:=I3ep[M,L,K,n,m,l,a3,a2,a1];


(* l, m, n are odd
   the sum is an infinite power series.

   The infinite power series should be computed using accelerator approach, e.g.,
   Levin u-transformation (J. S. Sims and S. A. Hagstrom, J. Phys. B, 37, 1519 (2004)

   method = 0: direct sum
          = 1: Levin u transformation 
*)
I3ep[K_,L_,M_,l_?OddQ,m_?OddQ,n_?OddQ,a1_,a2_,a3_,kmax_:30,method_:1]:=
	I3ep[K,L,M,l,m,n,a1,a2,a3,kmax,method]=
	Module[
		{A,S,C,int},

		Do[A[q] = 1/(2q+1)^2 \!\(
\*UnderoverscriptBox[\(\[Sum]\), \(i = 0\), \(\((l + 1)\)/2\)]\((pC[l, q, i] \(
\*UnderoverscriptBox[\(\[Sum]\), \(j = 0\), \(\((m + 1)\)/2\)]\((pC[m, q, j] \(
\*UnderoverscriptBox[\(\[Sum]\), \(k = 0\), \(\((n + 1)\)/2\)]\((pC[n, q, k]*\n\t\t\t\((pW[K + 2 + 2  q + 2  j + 2  k, L + 2 + 2  i + n - 2  k, M + 2 - 2  q + l - 2  i + m - 2  j, a1, a2, a3] + \n\t\t\t\ pW[K + 2 + 2  q + 2  j + 2  k, M + 2 + 2  i + m - 2  j, L + 2 - 2  q + l - 2  i + n - 2  k, a1, a3, a2] + \n\t\t\t\ pW[L + 2 + 2  q + 2  i + 2  k, K + 2 + 2  j + n - 2  k, M + 2 - 2  q + l - 2  i + m - 2  j, a2, a1, a3] + \n\t\t\t\ pW[L + 2 + 2  q + 2  i + 2  k, M + 2 + 2  j + l - 2  i, K + 2 - 2  q + m - 2  j + n - 2  k, a2, a3, a1] + \n\t\t\t\ pW[M + 2 + 2  q + 2  i + 2  j, K + 2 + 2  k + m - 2  j, L + 2 - 2  q + l - 2  i + n - 2  k, a3, a1, a2] + \n\t\t\t\ pW[M + 2 + 2  q + 2  i + 2  j, L + 2 + 2  k + l - 2  i, K + 2 - 2  q + m - 2  j + n - 2  k, a3, a2, a1])\))\)\))\)\))\)\)
		,{q,0,kmax}];

		Which[method == 0, 
				int = 64\[Pi]^3*\!\(
\*UnderoverscriptBox[\(\[Sum]\), \(q = 0\), \(kmax\)]\(A[q]\)\),
			  method == 1,
				S[0]=A[0];
				Do[S[j]=S[j-1]+A[j],{j,1,kmax}];

				Do[C[j]=(-1)^j Binomial[kmax,j](j+1)^(kmax-2) 1/A[j],{j,0,kmax}];
				int = 64\[Pi]^3*\!\(
\*UnderoverscriptBox[\(\[Sum]\), \(j = 0\), \(kmax\)]\((C[j]*S[j])\)\)/\!\(
\*UnderoverscriptBox[\(\[Sum]\), \(j = 0\), \(kmax\)]\(C[j]\)\)
		];
		int
	];



Clear[pVr];
pVr[m_,0,a_,b_]/;m>=0:=pVr[m,0,a,b]=1/b pA[m,a+b];
pVr[m_,n_,a_,b_]/;(m>=0 && m+n>=0):=pVr[m,n,a,b]=1/b (n*pVr[m,n-1,a,b]+pA[m+n,a+b]);

Clear[pWr];

pWr[0,0,0,a_,b_,r_]:=pWr[0,0,0,a,b,r]=1/((a+b+r)(b+r)r);
pWr[f_,g_,h_,a_,b_,r_]/;(f>=0 && f+g>=-1 && f+g+h>=-1):=pWr[f,g,h,a,b,r]=1/r (h*pWr[f,g,h-1,a,b,r]+pVr[f,g+h,a,b+r]);
pWr[f_,g_,h_,a_,b_,r_]/;(f>=0 && f+g>=0 && f+g+h>=-1):=pWr[f,g,h,a,b,r]=1/(b+r) (g*pWr[f,g-1,h,a,b,r]+h*pWr[f,g,h-1,a,b,r]+pVr[f+g,h,a+b,r]);
pWr[f_,g_,h_,a_,b_,r_]/;(f>=1 && f+g>=0 && f+g+h>=-1):=pWr[f,g,h,a,b,r]=1/(a+b+r) (f*pWr[f-1,g,h,a,b,r]+g*pWr[f,g-1,h,a,b,r]+h*pWr[f,g,h-1,a,b,r]);



Clear[Dw,Dhat];
Dw[wi_,wj_,wk_]:=Log[(wj+wk)/wi]Log[(wi+wj+wk)/(wj+wk)]-PolyLog[2,-(wi/(wj+wk))]-PolyLog[2,1-wi/(wj+wk)];
Dhat[w1_,w2_,w3_]:=1/2 (Dw[w1,w2,w3]+Dw[w2,w3,w1]+Dw[w3,w1,w2]);

Clear[I3e];

(* ------------------------------------------------------------------- *)
I3e[-1,-1,-1,-1,-1,-1,w1_,w2_,w3_]:=64\[Pi]^3*Dhat[w1,w2,w3]/(w1*w2*w3);

I3e[K_,L_,M_,-1,-1,-1,w1_,w2_,w3_]/;(K+L+M)<9 :=Module[
	{a1,a2,a3},
	(-1)^(K+L+M+1)*D[I3e[-1,-1,-1,-1,-1,-1,a1,a2,a3],
				{a1,K+1},{a2,L+1},{a3,M+1}]/.{a1->w1,a2->w2,a3->w3}
];

(* ------------------------------------------------------------------- *)
I3e[-1,-1,-1,0,0,-1,w1_,w2_,w3_]:=
	64\[Pi]^3*1/(w1*w2*(w1+w2)*w3^2);

I3e[K_,L_,M_,0,0,-1,w1_,w2_,w3_]/;(K+L+M)<9 :=Module[
	{a1,a2,a3},
	(-1)^(K+L+M+1)*D[I3e[-1,-1,-1,0,0,-1,a1,a2,a3],
				{a1,K+1},{a2,L+1},{a3,M+1}]/.{a1->w1,a2->w2,a3->w3}
];

(* ------------------------------------------------------------------- *)
I3e[-1,-1,-1,1,-1,-1,w1_,w2_,w3_]:=
	64\[Pi]^3*1/(w2^2 w3^2) ((w2^2+w3^2-w1^2)/(w1*w2*w3) Dhat[w1,w2,w3]-1/(w1+w2)-1/(w1+w3)+
				(w1-w2)/(w1*w2) Log[(w1+w2)/w3]+(w1-w3)/(w1*w3) Log[(w1+w3)/w2]+(w2+w3)/(w2*w3) Log[(w2+w3)/w1]);

I3e[K_,L_,M_,1,-1,-1,w1_,w2_,w3_]/;(K+L+M)<9 :=Module[
	{a1,a2,a3},
	(-1)^(K+L+M+1)*D[I3e[-1,-1,-1,1,-1,-1,a1,a2,a3],
				{a1,K+1},{a2,L+1},{a3,M+1}]/.{a1->w1,a2->w2,a3->w3}
];

(* ------------------------------------------------------------------- *)
I3e[-1,-1,-1,1,-1,1,w1_,w2_,w3_]:=
	64\[Pi]^3*1/(w1^3 w2^5 w3^3) ((w2^2 (2w1^2+w2^2+2w3^2)-3(w1^2-w3^2)^2)Dhat[w1,w2,w3]+
					w1((w3-w2)(w2^2+3w3^2)+3w1^2 (w2+w3))Log[(w2+w3)/w1]+
					w3((w1-w2)(w2^2+3w1^2)+3w3^2 (w1+w2))Log[(w1+w2)/w3]+
					w2(w1+w3)(3(w1-w3)^2-w2^2)Log[(w1+w3)/w2]+
					2w1*w2*w3*((w1*w2^2*w3)/(w1+w3)^3-2(w1+w3)+w2+(w2^2+3w1*w3)/(w1+w3)-w1^2/(w1+w2)-w3^2/(w2+w3)));

I3e[K_,L_,M_,1,-1,1,w1_,w2_,w3_]/;(K+L+M)<9 :=Module[
	{a1,a2,a3},
	(-1)^(K+L+M+1)*D[I3e[-1,-1,-1,1,-1,1,a1,a2,a3],
				{a1,K+1},{a2,L+1},{a3,M+1}]/.{a1->w1,a2->w2,a3->w3}
];

(* ------------------------------------------------------------------- *)
I3e[-1,-1,-1,1,1,-1,w1_,w2_,w3_]:=I3e[-1,-1,-1,1,-1,1,w1,w3,w2];

I3e[K_,L_,M_,1,1,-1,w1_,w2_,w3_]/;(K+L+M)<9 :=Module[
	{a1,a2,a3},
	(-1)^(K+L+M+1)*D[I3e[-1,-1,-1,1,1,-1,a1,a2,a3],
				{a1,K+1},{a2,L+1},{a3,M+1}]/.{a1->w1,a2->w2,a3->w3}
];

(* ------------------------------------------------------------------- *)



I3e[K_,L_,M_,l_,m_,n_,a1_,a2_,a3_]:=
	I3e[K,L,M,l,m,n,a1,a2,a3]=
	I3ep[K,L,M,l,m,n,a1,a2,a3];
